# Generated by Django 2.2.4 on 2019-09-10 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('RewardId', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('PlanId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Description', models.CharField(blank=True, max_length=500)),
                ('CreateDate', models.DateField(auto_now=True)),
                ('Rewards', models.CharField(blank=True, max_length=300)),
                ('Days', models.IntegerField(default=30)),
                ('Status', models.CharField(choices=[('C', 'Created'), ('P', 'In Process'), ('F', 'Finished'), ('D', 'Drop or Failed')], default='C', max_length=1)),
                ('Planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
