# Generated by Django 2.2.4 on 2019-09-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nailit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('TaskId', models.IntegerField(primary_key=True, serialize=False)),
                ('Step', models.IntegerField(default=0)),
                ('Description', models.CharField(blank=True, max_length=500)),
                ('PlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nailit.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='KeyResults',
            fields=[
                ('ResultId', models.IntegerField(primary_key=True, serialize=False)),
                ('FinishedSteps', models.CharField(blank=True, max_length=100)),
                ('CheckInDate', models.DateField(auto_now_add=True)),
                ('PlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nailit.Plans')),
            ],
        ),
    ]
